name: StuffMySonSaysApi Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
#    - name: Archive API build
#      uses: actions/upload-artifact@v2
#      with:
#        name: code-coverage-report
#        path: StuffMySonSaysApi.Main/bin/Debug/net6.0/*.*
#        retention-days: 8
